///Video Constants
export const YOUTUBE_SEARCH_TERM = 'YOUTUBE_SEARCH_TERM';
export const GET_TWITCH_VIDEOS = 'GET_TWITCH_VIDEOS';

///Eve-Mail
export const EVE_MAIL_FETCH_HEADERS = 'EVE_MAIL_FETCH_HEADERS';
export const EVE_MAIL_FETCH_CHARACTER_NAMES = 'EVE_MAIL_FETCH_CHARACTER_NAMES';
export const EVE_MAIL_WRITE_TOKENS = 'EVE_MAIL_WRITE_TOKENS';
export const EVE_MAIL_CHANGE_UPDATE_STAGE = 'EVE_MAIL_CHANGE_UPDATE_STAGE';
export const EVE_MAIL_GET_MAIL_BODY = 'EVE_MAIL_GET_MAIL_BODY';
export const EVE_MAIL_MAIL_HEADER_DISPLAY_CHANGE = 'EVE_MAIL_MAIL_HEADER_DISPLAY_CHANGE';
export const EVE_MAIL_AUX_WINDOW_DISPLAY_CHANGE = 'EVE_MAIL_AUX_WINDOW_DISPLAY_CHANGE';
export const EVE_MAIL_GET_NEW_ACCESS_TOKEN_WITH_REFRESH_TOKEN = 'EVE_MAIL_GET_NEW_ACCESS_TOKEN_WITH_REFRESH_TOKEN';
export const EVE_MAIL_WRITE_TOKENS_FROM_LOCAL_STORAGE = 'EVE_MAIL_WRITE_TOKENS_FROM_LOCAL_STORAGE';
export const EVE_MAIL_ADD_COMPOSE_SEND_ARRAY = 'EVE_MAIL_ADD_COMPOSE_SEND_ARRAY';
export const EVE_MAIL_REMOVE_COMPOSE_SEND_ARRAY = 'EVE_MAIL_REMOVE_COMPOSE_SEND_ARRAY';
export const EVE_MAIL_SORT_MAIL_HEADERS = 'EVE_MAIL_SORT_MAIL_HEADERS';

// Wow Constants
export const GET_WOW_RELM_STATUS = 'GET_WOW_RELM_STATUS';
